# Generated by Django 3.0.3 on 2020-06-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_v4', models.CharField(max_length=64)),
                ('Pos_v1', models.CharField(max_length=64)),
                ('Pos_v1_Info', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'v1',
            },
        ),
        migrations.CreateModel(
            name='V2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_v4', models.CharField(max_length=64)),
                ('Pos_v2', models.CharField(max_length=64)),
                ('Pos_v2_Info', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'v2',
            },
        ),
    ]
